apiVersion: v1
kind: Service
metadata:
  name: reservation-frontend
  namespace: reservation
spec:
  type: ClusterIP
  selector:
    app: reservation-frontend
  ports:
    - port: 80
      targetPort: 80
